export const classes = [
  {
    Nome: 'Introdução à Business Intelligence',
    Texto: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    Video: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    Audio: 'https://soundcloud.com/user/123456789',
    Tags: 'business intelligence, data analysis, data visualization',
  },
  {
    Nome: 'Fundamentos de Back-End Development',
    Texto: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    Video: 'https://www.youtube.com/watch?v=abc123',
    Audio: 'https://soundcloud.com/user/987654321',
    Tags: 'back-end development, server-side, databases',
  },
  {
    Nome: 'Introdução ao Front-End Development',
    Texto: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    Video: 'https://www.youtube.com/watch?v=xyz789',
    Audio: 'https://soundcloud.com/user/456123789',
    Tags: 'front-end development, web development, HTML, CSS, JavaScript',
  },
  {
    Nome: 'Segurança da Informação',
    Texto: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    Video: 'https://www.youtube.com/watch?v=uvw456',
    Audio: 'https://soundcloud.com/user/987654123',
    Tags: 'information security, cybersecurity, ethical hacking',
  },
  {
    Nome: 'Desenvolvimento de Aplicações Mobile',
    Texto: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    Video: 'https://www.youtube.com/watch?v=def789',
    Audio: 'https://soundcloud.com/user/123abc456',
    Tags: 'mobile app development, iOS, Android, React Native',
  },
  {
    Nome: 'Introdução à Inteligência Artificial',
    Texto: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    Video: 'https://www.youtube.com/watch?v=ghi789',
    Audio: 'https://soundcloud.com/user/abc123def',
    Tags: 'artificial intelligence, machine learning, neural networks',
  },
  {
    Nome: 'Desenvolvimento Web Full Stack',
    Texto: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    Video: 'https://www.youtube.com/watch?v=jkl456',
    Audio: 'https://soundcloud.com/user/789def123',
    Tags: 'full stack development, web development, front-end, back-end',
  },
  {
    Nome: 'Cloud Computing e Infraestrutura como Serviço',
    Texto: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    Video: 'https://www.youtube.com/watch?v=lmn789',
    Audio: 'https://soundcloud.com/user/def123abc',
    Tags: 'cloud computing, IaaS, virtualization, AWS, Azure, GCP',
  },
  {
    Nome: 'Desenvolvimento de Jogos',
    Texto: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    Video: 'https://www.youtube.com/watch?v=opq123',
    Audio: 'https://soundcloud.com/user/456abc789',
    Tags: 'game development, Unity, game design, 3D modeling',
  },
  {
    Nome: 'Análise de Dados e Mineração de Dados',
    Texto: 'Lorem ipsum dolor sit amet, consectetur adipiscing',
    Video: 'https://www.youtube.com/watch?v=lmn789',
    Audio: 'https://soundcloud.com/user/def123abc',
    Tags: 'data analysis, data mining, data visualization',
  },
]
